name: ansible-integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      icinga:
        image: jordan/icinga2
        ports:
        - 80:80
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: collections/ansible_collections/t_systems_mms/icinga_director
      - name: Install Ansible
        run: pip install ansible --disable-pip-version-check
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: test.yml
          directory: tests/integration/
