name: ansible-integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    container: rndmh3ro/docker-centos8-ansible:latest
    services:
      icinga:
        image: jordan/icinga2
        ports:
        - 80:80
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: collections/ansible_collections/t_systems_mms/icinga_director
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          ANSIBLE_COLLECTIONS_PATHS: ./collections:/home/runner/work/ansible-collection-icinga-director/collections/
        with:
          playbook: tests/integration/test.yml
        working_directory: /home/runner/work/ansible-collection-icinga-director/
