name: ansible-integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    container: rndmh3ro/docker-centos8-ansible:latest
    strategy:
      matrix:
        python_version: ['3.6']
    services:
      icinga:
        image: jordan/icinga2
        ports:
          - 80:80
          - 443:443
        env:
          ICINGA2_FEATURE_DIRECTOR_PASS: "icinga"
    steps:
      #- name: Set up Python ${{ matrix.python_version }}
      #  uses: actions/setup-python@v1
      #  with:
      #    python-version: ${{ matrix.python_version }}

      #- name: Install ansible base
      #  run: pip install ansible

      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible-collection-icinga-director/collections/ansible_collections/t_systems_mms/icinga_director

      - name: Run integration tests
        run: ansible-playbook tests/integration/test.yml -vvvvv
        env:
          ANSIBLE_COLLECTIONS_PATHS: ansible-collection-icinga-director/collections/:../../ansible-collection-icinga-director/collections/:collections/
